name: flutter_playground
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3


flutter:

  uses-material-design: true


